### ISSUE TITLE
can I use FINE for multi-objective optimization of energy systems? 

### ISSUE THREAD

**Issue by hangtianzhang** [FZJ-IEK3-VSA/FINE#33]
Hello, can I use FINE for multi-objective optimization of energy systems? I now want to make a calculation example that targets cost and carbon dioxide emissions. Thank you

**Comment by t-gross** [comment]
Thanks for your interest in FINE, and sorry for my late response.
At the moment, there is just one objective function integrated in FINE - that´s minimizing TAC.
So, it´s not possible to minimize both - TAC and CO2 emissions. 
If it´s not necessary to have both in the objective function, you can run your model with different CO2 reduction targets (using the yearlyLimit parameter).
