### ISSUE TITLE
Separate model init and model solve

### ISSUE THREAD

**Issue by l-kotzur** [FZJ-IEK3-VSA/FINE#4]
It would be great if the two steps of the pyomo.Concrete model initialization and parameterization could be separated from the model solving. Such, it would be possible to add custom constraints after the initialization process, or to output the resulting model without the requirement to solve it

**Comment by l-welder** [comment]
Hi Leander,
thank you for bringing this to my attention. I split the old optimize function into (a) a declareOptimizationProblem and (b) a new optimize function.  Additionally, I added a boolean to the new optimize function which, when True, calls the declareOptimizationFunction. In this way, the declareOptimizationProblem function does not have to be called and the setup is consistent with previous version.
