### ISSUE TITLE
[JOSS] Documentation - Community guidelines

### ISSUE THREAD

**Issue by GregorBecker** [FZJ-IEK3-VSA/FINE#50]
Hi, this issue is about the Community guidelines within the [JOSS Review 6274](https://github.com/openjournals/joss-reviews/issues/6274).

Please add a CONTRIBUTING.md and a CODE_OF_CONDUCT.md to your repository that describes how to handle feature & bug issues and pull requests to reduce the hurdle for possible contributors. For this purpose, you can use tools such as [contributing-gen](https://bttger.github.io/contributing-gen-web/).

In combination with moving the templates provided in the .gitlab folder to a .github folder, these would fulfill the community guideline ([Issue 48](https://github.com/FZJ-IEK3-VSA/FINE/issues/48)).

Kind regards
@GregorBecker

**Comment by t-gross** [comment]
Thank you for your feedback. We adjusted the section on how to contribute and added a CODE_OF_CONDUCT.md to our repository (currently available in develop-branch). 

Currently, there are still some ongoing developments in an internal gitlab-version of this repository. We need to discuss how to deal with this. Nevertheless, thanks for your comment.

**Comment by GregorBecker** [comment]
Dear @t-gross, 

the community guidelines look sufficient. Therefore, this issue can be closed.

Kind Regards,
@GregorBecker
