### ISSUE TITLE
FINE does not bring its dependencies anymore

### ISSUE THREAD

**Issue by maurerle** [FZJ-IEK3-VSA/FINE#52]
While it would be very cool to have this working with python 3.11 - it is unfortunately a dependency mess, as fine does reference the needed dependencies anymore.

This means, that we now have to keep track of needed dependencies outside of fine when installing it with `pip install fine`.

Would you be open for a PR which fixes this?

Obviously the following need to be added as deps into the pyproject.toml:

```
geopandas
# jupyter
# notebook
libpysal
# pip
descartes
glpk
openpyxl
matplotlib
xlrd
pyomo
numpy
pandas
networkx
scipy
scikit-learn>=1.2
xarray
rasterio
netcdf4
tsam
pwlf
psutil
gurobi-logtools
```

**Comment by k-knosala** [comment]
@maurerle Thank you for creating this issue!

We now allow python 3.10, 3.11 and 3.12 and added the dependencies to `pyproject.toml`  in [v2.3.6](https://github.com/FZJ-IEK3-VSA/FINE/releases/tag/v2.3.6).

We also added an explanation about the pip installtion in the README.

Feel free to open another issue if there are any other difficulties with the installation.
